title: SSL
description: Saudi SLL Competetion
baseurl: /jekyll-nagymaros
url: https://piazzai.github.io

permalink: pretty
theme: jekyll-nagymaros

home: /
copyright: Place Holder
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  